title: Open Source Covid-19
author: vilsbole
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We are a decentralised group of makers united to fight the
  the current pandemnic. We've raised over 13,000 DAI to fund
  the testing and shipping of open source masks and ventilators.

# social links
twitter_username: bneiluj # DO NOT include the @ character, or else the build will fail!
github_username: bneiluj # DO NOT include the @ character, or else the build will fail!

# project links:
ventilators: https://github.com/bneiluj/covid-19-open-source-ventilators
shields: https://github.com/bneiluj/covid-19-open-source-masks
telegram:
contact:
twitter: https://twitter.com/bneiluj
gitcoin: https://gitcoin.co/grants/578/open-source-covid-ventilator-oscv?tab=description

show_excerpts: false # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/

plugins:
  - jekyll-theme-minimal
  - jekyll-redirect-from

whitelist:
  - jekyll-theme-minimal
  - jekyll-redirect-from
