# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

group :jekyll_plugins do
  gem "github-pages", "202"
  gem "jekyll-theme-minimal", "~> 0.1.1"
  gem "jekyll-redirect-from"
end
